services:
  # Web服务配置
  - type: web
    name: vehicle-system
    env: python
    buildCommand: pip install -r requirements-vercel.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

# 数据库配置 
databases:
  - name: vehicle-db
    databaseName: vehicle
    user: vehicle_user
    plan: free